CORE = spc7110

VSRC = address.v cheat.v dac.v DCM_Scope.v main.v mcu_cmd.v msu.v rtc4513_emu.v sd_dma.v spi.v
VHSRC_PKG = SPC7110_DEC_PKG.vhd
VHSRC = FIFO_B2B.vhd FIFO_AXIS.vhd SPC7110_DEC_PKG.vhd SPC7110_DEC.vhd SPC7110_MULDIV.vhd SPC7110_FIFO.vhd SPC7110.vhd

COMMON_IP = dac_buf msu_databuf snescmd_buf

XIL_IP =
XIL_IPCORE_DIR = ipcore_dir

INT_IP = pll

include ../settings.mk
include ../common.mk
