CORE = spc7110

VSRC = address.v cheat.v clk_test.v dac.v rtc.v srtc.v main.v mcu_cmd.v msu.v sd_dma.v spi.v
VHSRC = FIFO_B2B.vhd FIFO_AXIS.vhd Golomb_0_Decoder.vhd Golomb_N_Decoder.vhd Input_Manager.vhd Output_Manager.vhd Probability_Estimator.vhd SPC7110.vhd Serializer.vhd

COMMON_IP = dac_buf msu_databuf snescmd_buf

INT_IP = pll

include ../settings.mk
include ../common.mk
