CORE = spc7110

VSRC = address.v cheat.v clk_test.v dac.v dcm.v main.v mcu_cmd.v msu.v sd_dma.v spi.v spc7110_alu.v spc7110_banked.v spc7110_dcu_arbiter.v spc7110_dcu.v spc7110_direct.v 
VHSRC =

COMMON_IP = dac_buf msu_databuf snescmd_buf

XIL_IP =
XIL_IPCORE_DIR = ipcore_dir

INT_IP = pll

include ../settings.mk
include ../common.mk
